#!/usr/bin/python3
from sys import argv
from math import sqrt
from multiprocessing import Pool

def find_factor(x):
    if x % 2 == 0:
        return (x//2, 2)
    for i in range(3, int(sqrt(x)) + 1, 2):
        if x % i == 0:
            return (x//i, i)
    return (-1, -1)

def main():
    with Pool(8) as pool:
        with open(argv[1], "r") as file:
                lists = pool.map(find_factor, [int(x) for x in file.readlines()])
                for x,y in lists:
                    print(f"{x*y}={x}*{y}")

if __name__ == "__main__":
    main()
