#!/usr/bin/python3
import sys

def find_factor(x):
    for i in range(2, int(x ** 0.5) + 1):
        if x % i == 0:
            return (x//i, i)

def main():
    with open(sys.argv[1], "r") as file:
        for x in file.readlines():
            value = int(x)
            v1, v2 = find_factor(value)
            print(f"{v1}*{v2}={value}")

if __name__ == "__main__":
    main()
